scene_generator:
  name: Scene Generator
  description: Generate a scene based on the state of specific entities in specified domains.
  fields:
    domains:
      description: The domains to be processed for generating the scene.
      example:
        - light
        - switch
        - fan
    attributes:
      description: The attributes of the entities to be processed.
      example:
        - brightness
        - color_temp
        - xy_color
        - rgb_color
    save_file:
      description: If set to true, the generated scene will be sent as a message using the 'notify.scene_generator' service. If false, the scene will be logged using logger.info.
      example: true
